version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
      MYSQL_USER: Habiba
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: task-management-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskdb
      SPRING_DATASOURCE_USERNAME: Habiba
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET_KEY: Wn3$g@2Zr9P!kL7e#Fq^xB1mV8tY*oJdUwC6hR0aNsX4MzEiTp
      JWT_EXPIRATION: 86400000
      EMAIL_USERNAME: ha2090245@gmail.com
      EMAIL_PASSWORD: lcqr lhda wtbc caik
    restart: always

volumes:
  mysql_data:
